In [1]:
import numpy as np
import pandas as pd
from sklearn.svm import SVR
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [3]:
data = pd.read_csv('ENERGYMETER2.csv')

In [4]:
data.columns = ["Vrms","Irms","PowerFactor","Power","Energy"]
df = pd.DataFrame(data)
df

Vrms  Irms  PowerFactor  Power  Energy
0    245.34  0.13            1  30.98    0.03
1    245.34  0.12            1  30.04    0.06
2    245.34  0.12            1  29.14    0.08
3    245.34  0.12            1  30.86    0.11
4    245.34  0.12            1  30.03    0.14
..      ...   ...          ...    ...     ...
514  245.34  0.13            1  30.88   12.30
515  245.34  0.12            1  30.57   12.33
516  245.34  0.13            1  30.34   12.35
517  245.34  0.13            1  31.08   12.38
518  245.34  0.12            1  30.47   12.40

[519 rows x 5 columns]

In [5]:
X = []
for i in range(len(df.Energy)) :
    X.append(2.5*i)
X
X = np.array(X)
X = X.reshape(-1,1)
X

array([[   0. ],
       [   2.5],
       [   5. ],
       [   7.5],
       [  10. ],
       [  12.5],
       [  15. ],
       [  17.5],
       [  20. ],
       [  22.5],
       [  25. ],
       [  27.5],
       [  30. ],
       [  32.5],
       [  35. ],
       [  37.5],
       [  40. ],
       [  42.5],
       [  45. ],
       [  47.5],
       [  50. ],
       [  52.5],
       [  55. ],
       [  57.5],
       [  60. ],
       [  62.5],
       [  65. ],
       [  67.5],
       [  70. ],
       [  72.5],
       [  75. ],
       [  77.5],
       [  80. ],
       [  82.5],
       [  85. ],
       [  87.5],
       [  90. ],
       [  92.5],
       [  95. ],
       [  97.5],
       [ 100. ],
       [ 102.5],
       [ 105. ],
       [ 107.5],
       [ 110. ],
       [ 112.5],
       [ 115. ],
       [ 117.5],
       [ 120. ],
       [ 122.5],
       [ 125. ],
       [ 127.5],
       [ 130. ],
       [ 132.5],
       [ 135. ],
       [ 137.5],
       [ 140. ],
       [ 142.5],
       [ 145. 

In [6]:
y = df.Energy
y = np.array(y)
y

array([ 0.03,  0.06,  0.08,  0.11,  0.14,  0.16,  0.19,  0.21,  0.24,
        0.26,  0.29,  0.32,  0.34,  0.37,  0.4 ,  0.43,  0.46,  0.49,
        0.52,  0.55,  0.58,  0.6 ,  0.62,  0.65,  0.67,  0.7 ,  0.72,
        0.75,  0.77,  0.8 ,  0.82,  0.85,  0.87,  0.9 ,  0.93,  0.95,
        0.98,  1.  ,  1.03,  1.05,  1.07,  1.09,  1.12,  1.15,  1.15,
        1.15,  1.15,  1.15,  1.15,  1.15,  1.17,  1.2 ,  1.22,  1.25,
        1.27,  1.3 ,  1.32,  1.35,  1.37,  1.4 ,  1.42,  1.45,  1.47,
        1.5 ,  1.52,  1.55,  1.58,  1.6 ,  1.63,  1.65,  1.68,  1.7 ,
        1.73,  1.75,  1.78,  1.8 ,  1.83,  1.85,  1.88,  1.9 ,  1.93,
        1.96,  1.98,  2.01,  2.03,  2.06,  2.08,  2.11,  2.12,  2.15,
        2.15,  2.15,  2.15,  2.15,  2.15,  2.15,  2.17,  2.2 ,  2.22,
        2.25,  2.27,  2.3 ,  2.33,  2.35,  2.38,  2.4 ,  2.43,  2.45,
        2.48,  2.51,  2.53,  2.56,  2.58,  2.61,  2.63,  2.66,  2.69,
        2.71,  2.74,  2.76,  2.79,  2.81,  2.84,  2.86,  2.89,  2.92,
        2.94,  2.97,

In [7]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.6)

In [8]:
svr = SVR(kernel='linear')
svr.fit(X_train,y_train)

SVR(kernel='linear')

In [9]:
y_pred = svr.predict(X_test)
y_pred

array([ 3.65518086,  1.15317749,  6.94352813,  0.79574844,  6.7290707 ,
        8.7783306 ,  7.27712858, 10.99439072,  9.15958826,  5.13255427,
        7.30095719,  4.46535337, 11.23267676, 10.04124658,  3.03563717,
        5.3231831 ,  6.22867003,  1.74889258,  4.60832499,  6.06186981,
        7.53924322,  9.32638848,  2.98797996,  9.63616032,  1.72506398,
       12.2334781 ,  0.91489146,  6.84821372,  5.56146913,  4.84661103,
        9.68381753, 10.58930446,  0.36683358,  5.84741237,  9.82678915,
       11.66159162,  7.20564277,  9.4455315 ,  0.31917637,  9.23107407,
        3.44072343,  2.03483582,  3.2739232 ,  6.0380412 ,  9.4693601 ,
       11.08970514,  4.56066779,  9.01661663,  8.63535898,  8.20644412,
        7.77752925, 10.94673352,  7.87284367, 10.20804681,  5.63295494,
        1.67740677,  7.61072903,  1.34380632,  6.37164165,  0.24769056,
       10.32718983,  5.44232612,  4.58449639,  9.35021708,  8.37324434,
        5.01341125, -0.06208128,  2.91649415,  7.34861439,  1.24

In [10]:
r2 = r2_score(y_pred,y_test)
r2

0.9995478741687918

In [11]:
rows = X.shape[0]
rows
x = []
x.append(5*X[rows-1])
start = x[0]

In [12]:
for i in range(1,20):
    start =  start+3
    x.append(start)
x

[array([6475.]),
 array([6478.]),
 array([6481.]),
 array([6484.]),
 array([6487.]),
 array([6490.]),
 array([6493.]),
 array([6496.]),
 array([6499.]),
 array([6502.]),
 array([6505.]),
 array([6508.]),
 array([6511.]),
 array([6514.]),
 array([6517.]),
 array([6520.]),
 array([6523.]),
 array([6526.]),
 array([6529.]),
 array([6532.])]

In [13]:
y_predicted = svr.predict(x)
y_predicted

array([61.65400168, 61.682596  , 61.71119033, 61.73978465, 61.76837897,
       61.7969733 , 61.82556762, 61.85416195, 61.88275627, 61.91135059,
       61.93994492, 61.96853925, 61.99713357, 62.02572789, 62.05432221,
       62.08291654, 62.11151087, 62.14010519, 62.16869951, 62.19729383])

In [18]:
out = [10*X[rows-1],15*X[rows-1],20*X[rows-1]]
output = []
for i in out :
    output.append(i/60)
output

[array([215.83333333]), array([323.75]), array([431.66666667])]

In [20]:
y_predi = svr.predict(out)
y_predi

array([123.37008464, 185.08616761, 246.80225056])

In [21]:
energy_in_units = []
for i in y_predi :
    energy_in_units.append(i/1000)
energy_in_units

[0.12337008463722644, 0.1850861676050442, 0.24680225055796084]

In [22]:
price = []
for i in energy_in_units :
    price.append(i*3)
price

[0.37011025391167934, 0.5552585028151327, 0.7404067516738826]

In [27]:
result = {'Time(in minutes)':[215.83,323.75,431.66],'Energy(in units)':energy_in_units,'Price(in Rupees)':price}
res = pd.DataFrame(result)
res

Time(in minutes)  Energy(in units)  Price(in Rupees)
0            215.83          0.123370          0.370110
1            323.75          0.185086          0.555259
2            431.66          0.246802          0.740407